# Generated by Django 4.2.3 on 2023-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_name", models.CharField(max_length=100, verbose_name="Name")),
                ("stu_class", models.CharField(max_length=100, verbose_name="Class")),
                ("stu_email", models.EmailField(max_length=254)),
                ("stu_mobile", models.IntegerField()),
            ],
        ),
    ]
