# Generated by Django 4.2.3 on 2023-07-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dep_name", models.CharField(max_length=100, verbose_name="Name")),
                ("description", models.TextField(max_length=200, verbose_name="Desc")),
            ],
        ),
    ]
