# Generated by Django 4.2.3 on 2023-07-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_department"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department",
            new_name="DepartmentModel",
        ),
    ]
