# Generated by Django 4.2.3 on 2024-01-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentmodel_stu_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='stu_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.departmentmodel'),
        ),
    ]
